FROM python:3.9-slim
WORKDIR /app
COPY worker/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY worker /app/worker
CMD ["celery", "-A", "worker.tasks", "worker", "--loglevel=info"]
