FROM python:3.9-slim 
WORKDIR /app 
COPY jobmaster/requirements.txt /app/ 
RUN pip install --no-cache-dir -r requirements.txt 
COPY jobmaster/ /app/jobmaster/ 
CMD ["uvicorn", "jobmaster.main:app", "--host", "0.0.0.0", "--port", "8000"]